word_list = [
    'tumour',
    'subway',
    'proposal',
    'candidate',
    'sodium',
    'conductor',
    'dismiss',
    'represent',
    'champion',
    'headline',
    'relieve',
    'reactor',
    'feather',
    'electronics',
    'vacuum',
    'harbor',
    'aviation',
    'remember',
    'network',
    'auction',
    'incongruous',
    'manager',
    'research',
    'governor',
    'useful',
    'oppose',
    'indication',
    'reluctance',
    'valley',
    'moment'
]

christopher_nolan_films = [
    'Tenet', 
    'Interstellar', 
    'Dunkirk', 
    'The Dark Knight Rises', 
    'The Dark Knight', 
    'Batman Begins', 
    'Inception', 
    'The Prestige', 
    'Memento', 
    'Following'
]
